# Generated by Django 2.0.6 on 2020-03-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0006_event_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/static/img/abcimage.jpg', upload_to=''),
        ),
    ]
